---
# - name: get ip address
#   command: ifconfig
- name: Read hosts file
  command: cat /etc/hosts

- name: Install packages
  apt: pkg=htop state=latest
  become: yes

- name: Install packages essential for development
  become: yes
  apt: pkg="{{ item }}" state=latest
  with_items:
  - proguard
  - fastjar
  - jaligner
  - jarwrapper
  - visualvm
  - gradle
